import "./globals.css";
import { Inter, Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
import { Providers } from "./providers";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body  className={geistSans.className}>\
        <Providers>
        <Header />
        <main className="min-h-screen">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
